name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - main

jobs:
  docker:
    if: github.event_name == 'push' && (
         (github.ref == 'refs/heads/dev' && github.event.before != github.event.after) ||
         (github.ref == 'refs/heads/main' && github.event.before != github.event.after)
       )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERRHUB_TOKEN }}

      - name: Determine tag
        id: tag
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "tag=stable" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: malewis0611/flasktts:${{ steps.tag.outputs.tag }}
