name: Versioning for preprocessor.py

on:
  push:
    branches:
      - dev
    paths:
      - "preprocessor.py"

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git Authentication
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git config --global credential.helper store
          echo "https://${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          chmod 600 ~/.git-credentials

      - name: Determine Changed Files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD -- preprocessor.py)
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Update Version for preprocessor.py
        run: |
          VERSION_FILE="version.json"
          BRANCH_NAME="dev"
          FILE="preprocessor.py"
          JSON_KEY="Preprocessor"
          
          # Check if the file is part of the changes
          if echo "$CHANGED_FILES" | grep -q "$FILE"; then
            CURRENT_VERSION=$(jq -r ".\"$JSON_KEY\"" $VERSION_FILE)
            IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
            ((MAJOR++))
            MINOR=0
            PATCH=0
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
            jq ".\"$JSON_KEY\" = \"$NEW_VERSION\"" $VERSION_FILE > tmp.json && mv tmp.json $VERSION_FILE
          fi

      - name: Commit and Push Changes
        run: |
          git add version.json
          git commit -m "Auto-incremented Preprocessor version [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
