name: Versioning

on:
  push:
    branches:
      - dev

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Determine Changed Files
        id: changed-files
        run: |
          echo "Checking for file changes..."
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | tr '\n' ' ')
          else
            echo "First commit detected. Treating all files as changed."
            CHANGED_FILES=$(git ls-files | tr '\n' ' ')
          fi
          echo "Changed files: $CHANGED_FILES"
          
          # Store properly formatted changed files
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Update Version
        run: |
          set -e  # Exit on error

          VERSION_FILE="version.json"
          BRANCH_NAME="${{ github.ref_name }}"

          echo "Processing version updates..."
          echo "Branch: $BRANCH_NAME"

          # Verify JSON file exists
          if [[ ! -f $VERSION_FILE ]]; then
            echo "Error: $VERSION_FILE not found!"
            exit 1
          fi

          # Ensure JSON is valid
          if ! jq empty $VERSION_FILE >/dev/null 2>&1; then
            echo "Error: $VERSION_FILE is not valid JSON!"
            cat $VERSION_FILE
            exit 1
          fi

          increment_version() {
            FILE=$1
            JSON_KEY=$2

            if echo "$CHANGED_FILES" | grep -q "$FILE"; then
              echo "Detected change in $FILE"

              CURRENT_VERSION=$(jq -r ".\"$JSON_KEY\"" $VERSION_FILE)

              if [[ ! $CURRENT_VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                echo "Error: Invalid version format for $JSON_KEY: '$CURRENT_VERSION'"
                exit 1
              fi

              echo "Current $JSON_KEY version: $CURRENT_VERSION"

              IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

              if [[ "$BRANCH_NAME" == *"feature"* ]]; then
                ((MAJOR++)); MINOR=0; PATCH=0
                echo "Feature branch detected - Incrementing MAJOR version"
              elif [[ "$BRANCH_NAME" == *"enhancement"* ]]; then
                ((MINOR++)); PATCH=0
                echo "Enhancement branch detected - Incrementing MINOR version"
              else
                ((PATCH++))
                echo "Default behavior - Incrementing PATCH version"
              fi

              NEW_VERSION="$MAJOR.$MINOR.$PATCH"
              echo "Updated $JSON_KEY version: $NEW_VERSION"

              jq ".\"$JSON_KEY\" = \"$NEW_VERSION\"" $VERSION_FILE > tmp.json && mv tmp.json $VERSION_FILE
            else
              echo "No changes detected in $FILE, skipping version update for $JSON_KEY."
            fi
          }

          # Always increment patch if pushed directly to dev
          if [[ "$BRANCH_NAME" == "dev" ]]; then
            echo "Direct push to dev - Forcing PATCH increment for all tracked files."
            for KEY in "App_version" "Preprocessor" "TTS Engine"; do
              CURRENT_VERSION=$(jq -r ".\"$KEY\"" $VERSION_FILE)
              IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
              ((PATCH++))
              NEW_VERSION="$MAJOR.$MINOR.$PATCH"
              jq ".\"$KEY\" = \"$NEW_VERSION\"" $VERSION_FILE > tmp.json && mv tmp.json $VERSION_FILE
            done
          else
            increment_version "app.py" "App_version"
            increment_version "preprocessor.py" "Preprocessor"
            increment_version "tts.py" "TTS Engine"
          fi

      - name: Commit and Push Changes
        run: |
          if ! git diff --quiet; then
            echo "Version changes detected, committing..."
            git add version.json
            git commit -m "Auto-increment version [skip ci]"
            git push
          else
            echo "No version changes detected, skipping commit."
          fi
