name: Versioning

on:
  push:
    branches:
      - dev

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Determine Changed Files
        id: changed-files
        run: |
          echo "Checking for file changes..."
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
          else
            echo "First commit detected. Treating all files as changed."
            CHANGED_FILES=$(git ls-files)
          fi
          echo "Changed files: $CHANGED_FILES"
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Update Version
        run: |
          set -e  # Exit on error

          VERSION_FILE="version.json"
          BRANCH_NAME="${{ github.ref_name }}"

          echo "Processing version updates..."
          echo "Branch
